# Generated by Django 2.2 on 2021-10-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Health_Be', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='patients',
            new_name='patient',
        ),
    ]
