# Generated by Django 2.2 on 2021-10-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Health_Be', '0004_historicalvitalsigns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvitalsigns',
            old_name='blood_pressure',
            new_name='oxygen_saturation_level',
        ),
        migrations.RenameField(
            model_name='vitalsigns',
            old_name='blood_pressure',
            new_name='oxygen_saturation_level',
        ),
        migrations.AlterField(
            model_name='historicalvitalsigns',
            name='covid_symptoms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='covid_symptoms',
            field=models.BooleanField(default=False),
        ),
    ]
