# Generated by Django 2.2 on 2021-10-14 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Health_Be', '0006_auto_20211014_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvitalsigns',
            name='patients',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='IoT_Health_Be.Patient'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='patients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_vitalsign', to='IoT_Health_Be.Patient'),
        ),
    ]
