# Generated by Django 2.2 on 2021-10-14 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Health_Be', '0008_auto_20211014_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitalsigns', to='IoT_Health_Be.Device'),
        ),
    ]
