# Generated by Django 2.2 on 2021-10-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Health_Be', '0009_auto_20211014_0238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitalsigns',
            options={'verbose_name_plural': 'VitalSigns'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='covid_positive',
            field=models.BooleanField(default=False),
        ),
    ]
