# Generated by Django 2.2 on 2021-10-14 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Health_Be', '0010_auto_20211014_0248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitalsigns',
            options={'verbose_name_plural': 'Vital Sign Readings (Per Device)'},
        ),
    ]
