# Generated by Django 2.2 on 2021-10-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Health_Be', '0011_auto_20211014_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_description',
            field=models.TextField(blank=True),
        ),
    ]
