# Generated by Django 2.2 on 2021-10-14 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Health_Be', '0013_remove_vitalsigns_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vitalsigns',
            old_name='created_at',
            new_name='measured_at',
        ),
    ]
