# Generated by Django 2.2 on 2021-10-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Health_Be', '0014_auto_20211014_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
