# Generated by Django 2.2 on 2021-10-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Health_Be', '0015_auto_20211014_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='unique_id',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
