# Generated by Django 2.2 on 2021-10-14 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Health_Be', '0017_vitalsigns_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vitalsigns',
            old_name='patient',
            new_name='patients_vitalsign',
        ),
    ]
