# Generated by Django 2.2 on 2021-10-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Health_Be', '0019_remove_vitalsigns_patients_vitalsign'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_battery',
            field=models.IntegerField(default=0),
        ),
    ]
