# Generated by Django 2.2 on 2021-10-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Health_Be', '0020_device_device_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='oxygen_saturation_level',
            field=models.FloatField(),
        ),
    ]
